### ISSUE TITLE
Retry on time out

### ISSUE THREAD

**Issue by RichardWright** [jmcdo29/retryable-http-nestjs#1]
How would this retry handle a connection error or a timeout? I've got the code using a real http client now and it goes straight to the catch and exits the retry

**Comment by jmcdo29** [comment]
You can change out the `retry` for a `retryWhen` method that retries on all errors and doesn't rely on the return of the `HttpService`. it could look somehting like this:
```ts
getGoogleBad(): Observable<any> {
    return this.httpService
      .get('https://httpstat.us/504', { validateStatus: null, timeout: 1 })
      .pipe(
        mergeMap(val => {
          if (val.status >= 400) {
            return throwError(`${val.status} returned from http call`);
          }
          return of(val.data);
        }),
        retryWhen(this.retry()),
        catchError(err => {
          console.log('IN CATCH');
          return of(err);
        }),
      );
  }

  retry() {
    return (attempts: Observable<any>) => attempts.pipe(
      merghttps://github.com/nestjs/graphqleMap((error, i) => {
        console.log('retry merge map');
        const retryAttempt = i + 1;
        if (retryAttempt > 3) {
          console.log('too many attempts. throwing error');
          return throwError(error);
        }
        return timer(0);
      })
    );
  }
```
Both methods are a part of the same class, but they could be separated if you wanted. You'll probably want to add more robustness to it. [More info on retryWhen here](https://www.learnrxjs.io/operators/error_handling/retrywhen.html)

**Comment by jmcdo29** [comment]
Closing this issue. If you still need more help, please let me know
